<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/26
 * Time: 10:24
 */
namespace app\index\widget;

use think\Controller;

class Blog extends Controller{
    public function header(){
        return $this->fetch('common/header');
    }

    public function footer(){
        return $this->fetch('common/footer');
    }


    public function right(){
        return $this->fetch('common/right');
    }
    /**
     * 构造方法
     */
    public function _initialize()
    {
        //父类
        parent::_initialize(); // TODO: Change the autogenerated stub
        //栏目
        $cateData = $this->getCateData();
        //搜索
        $searchData = $this->search();
        //推荐阅读
        $readData = $this->read();
        //热门点击
        $clickData = $this->hotClick();
        $this->assign('cateData',$cateData);
        $this->assign('searchData',$searchData);
        $this->assign('readData',$readData);
        $this->assign('clickData',$clickData);
    }
    /**
     * 查询所有栏目
     */
    public function getCateData(){
        $cateData = db('cate')->select();
        return $cateData;
    }

    /**
     * 搜索
     */
    public function search(){
        $searchData = db('article')->select();
        return $searchData;
    }
    /**
     * 推荐阅读
     */
    public function read(){
        $readData = db('article')->field('id,title')->where(['state'=>1])->order('id desc')->limit(4)->select();
        return $readData;
    }
    /**
     * 热门点击
     */
    public function hotClick(){
        $clickData = db('article')->field('id,title')->order('click desc')->limit(4)->select();
        return $clickData;
    }


}