<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/26
 * Time: 10:24
 */
namespace app\admin\widget;

use think\Controller;

class Blog extends Controller{
    public function header(){
        return $this->fetch('common/header');
    }

    public function left(){
        return $this->fetch('common/left');
    }

    /**
     * 构造方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->islogin();
    }

    /**
     * 判断是否已经登录
     */
    public function islogin(){
        $admin =session('admin');
        if(!isset($admin) || !$admin['id']){
            return $this->error('请先登录...',url('Login/index'));
        }
    }

}